services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: komsync-frontend
    restart: unless-stopped
    environment:
      BACKEND_UPSTREAM: ${BACKEND_UPSTREAM:-http://45.10.41.189:5237}
      PROD_ENV_VITE_BACKEND_ORIGIN: ${PROD_ENV_VITE_BACKEND_ORIGIN:-http://localhost:5237}
      PROD_ENV_VITE_API_PREFIX: ${PROD_ENV_VITE_API_PREFIX:-/api/v1}
    ports:
      - "80:80"
